bool publish_tf false   # publish the transform once
string base_frame_id 'camera_link'    # the transform is with respect to this frame id
string marker_frame_id 'aruco_marker'    # the transform is created with this frame id
int64 marker_id # Marker id of the aruco frame
---
bool success
geometry_msgs/TransformStamped transform