name: erf_demo

services:
  pose_estimation-server:
    extends:
      file: ${POSE_EST_SRC_DIR}/docker/docker-compose.yml
      service: pose_estimation-server

  pose_estimation-client:
    container_name: pose_estimation-client
    depends_on:
      pose_estimation-server:
          condition: service_started
    image: pose_estimation:latest
    working_dir: /home/ros/target_ws  # prebuilt ros workspace
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
    network_mode: host
    volumes:
      # For real pose estimation
      # - /home/coresense/SAMXL/coresense-ws/src/coresense-description/urdf/coby_env.xacro:/home/ros/urdf/coby_env.xacro  
      
      # For testing (also default behaviour)
      - ${POSE_EST_SRC_DIR}/aruco_pose_estimation/test/coby_env.xacro:/home/ros/urdf/coby_env.xacro 

      # so you can modify launch file at host during testing
      - ${POSE_EST_SRC_DIR}/aruco_pose_estimation/launch:/home/ros/target_ws/install/aruco_pose_estimation/share/aruco_pose_estimation/launch
    ipc: host
    command: /bin/bash -c 'source install/setup.bash && ros2 launch aruco_pose_estimation pose_estimation_client.launch.xml'
    